lib/ttfunk/subset/base.rb
lib/ttfunk/table/name.rb
spec/integration/subset_spec.rb

TTFunk used to generate semi-random subset font names. The name you'd get depended on the order/number of times you serialise your subsets.
Now subset font name only depends on the actual content of the subset.
As a bonus we're getting rid of a class var and as a result improve thread safety.

Consistent subset font names

---

.rubocop.yml
Rakefile
examples/metrics.rb

Currently, the CI has failed with rubocop offences. Here's a patch fixing those offences.

Fix code style to pass CI building

---

lib/ttfunk/table.rb

Here's a patch fixing the following Ruby warning:
```
lib/ruby/gems/2.4.0/gems/ttfunk-1.5.1/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
```

Fix Ruby Warnings

---

.travis.yml

Ruby 2.1 is no longer maintained.
cf #46

Remove ruby 2.1 from CI, add 2.5.

---

lib/ttfunk/subset/base.rb
spec/integration/subset_spec.rb

When encoding a font subset, the `search_range` field should be calculated as [`(maximum power of 2 <= numTables)*16`](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html#Directory).
Currently TTFunk is correctly calculating the maximum power of two (`2^x`), but then instead of setting `search_range` to the actual value of `2^x * 16`, it sets it to `x * 16`, which is not correct.
The incorrect entry for `search_range` causes the font to fail [OpenType Sanitizer (OTS)](https://github.com/khaledhosny/ots) validation. Because OTS is used in both Chrome and Firefox, the validation error means that the subset font generated with TTFunk currently cannot be used in the browser.
**Testing**
To reproduce the issue generate a new subset and save it to disk. Then run the OTS …

Fix calculation of search_range for font subsets.

---

lib/ttfunk/subset/unicode.rb
spec/integration/subset_spec.rb

The `TTFunk::Subset::Unicode#includes?(char)` method is trying to invoke `#includes(char)` on the underlying `Set` object, but `Set` does not respond to `#includes`.
This is most likely just a typo and should be using `#include?` instead.
**Testing**
To reproduce the issue:
```ruby
require 'ttfunk'
require 'ttfunk/subset'
font = TTFunk::File.open('myfont.ttf')
subset = TTFunk::Subset.for(font, :unicode)
subset.includes?(42)
```
The above fails with ``NoMethodError: undefined method `includes' for #<Set: {}>``.

Fix typo in TTFunk::Subset::Unicode#includes?

---

lib/ttfunk/subset/base.rb
spec/integration/subset_spec.rb

According to [the spec](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html#Directory), entries in the table directory must be sorted in ascending order by tag.
If the entries are not correctly sorted, OpenType Sanitizer check emits warnings, which can be seen in the browser console if font is used in browser which utilizes OTS (Chrome, Firefox).
**Testing**
To test this generate a new subset and save it to disk. Then run the OTS validator on it.
```ruby
require 'ttfunk'
require 'ttfunk/subset'
font = TTFunk::File.open('myfont.ttf')
subset = TTFunk::Subset.for(font, :unicode)
subset.use(97)
File.write('mysubset.ttf', subset.encode, mode: 'wb')
```
Install [OTS](https://github.com/khaledhosny/ots) and run `ots-sanitize`:
```bash
$ ots-sanitize mysubset.ttf
> ERROR …
```

Order tables by tag when generating font subset.

---

lib/ttfunk/table/cmap/format04.rb
spec/integration/subset_spec.rb

OpenType Sanitizer complains if the final code (`0xFFFF`) maps to a glyph index outside the range of glyphs in the subset.
[The spec](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html) suggests to map the code `0xFFFF` to glyph zero.
**Testing**:
To reproduce the issue generate a new subset and save it to disk. Then run the OTS validator on it.
```ruby
require 'ttfunk'
require 'ttfunk/subset'
font = TTFunk::File.open('myfont.ttf')
subset = TTFunk::Subset.for(font, :unicode)
subset.use(97)
File.write('mysubset.ttf', subset.encode, mode: 'wb')
```
Install [OTS](https://github.com/khaledhosny/ots) and run `ots-sanitize`:
```bash
$ ots-sanitize mysubset.ttf
> ERROR: cmap: Range glyph reference too high (65535 > 1)
> ERROR at src/cmap.cc:811 (Parse)
> ERROR at …
```

Map the 0xFFFF char code to glyph 0 in cmap format 4.

---

lib/ttfunk/table/name.rb
spec/integration/subset_spec.rb

Microsoft OpenType specification says that name records should be sorted by: platform_id, then platform_specific_id, then language_id, and finally by name_id.
The OpenType Sanitizer, which is used by browsers such as Chrome and Firefox to validate fonts before allowing them to be used in web pages, prints warnings if name records are not ordered.
**Testing**:
To reproduce the issue generate a new subset and save it to disk. Then run the OTS validator on it.
```ruby
require 'ttfunk'
require 'ttfunk/subset'
font = TTFunk::File.open('myfont.ttf')
subset = TTFunk::Subset.for(font, :unicode)
subset.use(97)
File.write('mysubset.ttf', subset.encode, mode: 'wb')
```
Install [OTS](https://github.com/khaledhosny/ots) and run `ots-sanitize`:
```bash
$ ots-sanitize mysubset.ttf
> WARNING: name: name …
```

Sort name table entries when generating subset font.

---

lib/ttfunk/directory.rb
lib/ttfunk/encoding/mac_roman.rb
lib/ttfunk/encoding/windows_1252.rb
lib/ttfunk/table/cmap.rb
lib/ttfunk/table/cmap/format04.rb
lib/ttfunk/table/hmtx.rb
lib/ttfunk/table/name.rb

_**This pull request is part of a larger effort to bring OTF support to TTFunk. See https://github.com/prawnpdf/ttfunk/issues/53 for details.**_
Higlights of this PR:
1. Fix `Directory` so it parses the correct fields (I'm not even sure what `scaler_type` means or where it came from, I can't find it in any documentation).
2. Remove `POSTSCRIPT_GLYPH_MAPPING` constants from the Mac Roman and Windows 1252 subsets since they appear to not be used anywhere.
3. Take the head table's `index_to_loc_format` field into consideration when encoding.
4. Refactor the name table to be a little more object-oriented.

Minor fixes and small refactorings

---

lib/ttfunk.rb
lib/ttfunk/table/dsig.rb
lib/ttfunk/ttf_encoder.rb
spec/ttfunk/table/dsig_spec.rb

_**This pull request is part of a larger effort to bring OTF support to TTFunk. See https://github.com/prawnpdf/ttfunk/issues/53 for details.**_
The only issue of note in this PR is that re-encoding the DSIG table will effectively remove all signatures from the font. Should we consider re-signing them with some TTFunk private key? My inclination is to not worry about it, at least for now.

Support the DSIG table

---

.travis.yml

This also changes the Travis CI config to include the same JRuby versions as pdf-core and prawn.

Add testing with Ruby 2.6

---

lib/ttfunk.rb
lib/ttfunk/aggregate.rb
lib/ttfunk/encoded_string.rb
lib/ttfunk/max.rb
lib/ttfunk/min.rb
lib/ttfunk/subset/base.rb
lib/ttfunk/subset/code_page.rb
lib/ttfunk/subset/unicode.rb
lib/ttfunk/sum.rb
lib/ttfunk/table/cmap/subtable.rb
lib/ttfunk/table/glyf.rb
lib/ttfunk/table/glyf/compound.rb
lib/ttfunk/table/glyf/path_based.rb
lib/ttfunk/table/glyf/simple.rb
lib/ttfunk/table/head.rb
lib/ttfunk/table/hhea.rb
lib/ttfunk/table/maxp.rb
lib/ttfunk/table/os2.rb
lib/ttfunk/ttf_encoder.rb
spec/integration/subset_spec.rb
spec/ttfunk/ttf_encoder_spec.rb

_**This pull request is part of a larger effort to bring OTF support to TTFunk. See https://github.com/prawnpdf/ttfunk/issues/53 for details.**_
This PR augments TTFunk's ability to calculate font metrics for both postscript fonts (i.e. "normal" fonts) and CFF-flavored fonts. It updates the glyf, hhea, head, maxp, and os/2 tables specifically.

Compute statistics for CFF fonts

---

lib/ttfunk/table/maxp.rb
spec/ttfunk/ttf_encoder_spec.rb

See: https://github.com/prawnpdf/ttfunk/issues/53#issuecomment-570890100
I'm baffled as to how this got past FontValidator, but it did. In fact it turns out basically all our maxp calculations are wrong. Fortunately most font display systems don't care, but we should probably work on computing correct max profile statistics :/

Fix maxp table encoding causing ghostscript error

---

lib/ttfunk/table/maxp.rb
spec/ttfunk/ttf_encoder_spec.rb

Although they caused [an issue](https://github.com/prawnpdf/ttfunk/issues/53#issuecomment-570890100), we thought the changes to maxp would ultimately be ok. Sadly that is not the case. Several other issues have been reported using Acrobat Reader on Windows:
https://github.com/prawnpdf/prawn/issues/1142
https://github.com/prawnpdf/ttfunk/issues/74
https://github.com/prawnpdf/ttfunk/issues/73
https://github.com/prawnpdf/ttfunk/issues/72
I was able to reproduce the issue on Windows and can confirm it is fixed by reverting the maxp code I introduced in 1.6.0.

Revert maxp to pre-1.6

---

lib/ttfunk/collection.rb
spec/integration/collection_spec.rb

TTF files can already be read from an IO object, this pull request does the same for TTC files

Allow TTC files to be read from IO object

---

CHANGELOG.md
ttfunk.gemspec

Ruby set to release v3.0 as usual in December of 2020
I think this gem should allow usage of ruby v3.0
Not sure if I should add some CI for ruby-head, since there maybe failures until stable release

Allow gem installation on ruby 3.0

---

lib/ttfunk/subset/code_page.rb
lib/ttfunk/subset_collection.rb

I ran a benchmark using Prawn together with a TrueType font handled by
ttfunk which allocated a staggering 107 million objects (compared to 1.6
million objects for the same benchmark using HexaPDF).
A 5min investigation revealed two spots that when optimized reduced the
number to about 32 million objects.
* TTFunk::Subset::CodePage#from_unicode:
Don't create an array and use #pack to convert a codepoint to a
character, just add the codepoint directly, saving an array allocation.
Furthermore, the created string can be modified using #encode! since
it is thrown away anyway.
* TTFunk::SubsetCollection#use:
The inner loop is called many times. By using a while loop instead of
an iterator with a block we avoid allocating and calling the block.

Reduce memory allocations and enhance performance

---

lib/ttfunk/table/os2.rb

fix #82
Original code takes `O(N * M)` time  where N is UNICODE_RANGES size and M is code_map keys size.
Improved code takes `O(max(N, M))` time.
Original code calls `r.cover?` with all pair of `UNICODE_RANGES` and `code_map keys`.
This takes `O(N * M)` time.
If `UNICODE_RANGES` and `code_map keys` are both sorted, first `UNICODE_RANGE` contains some `code_map keys` of the head flagment (or empty), next `UNICODE_RANGE` contains next flagment, and so on.
This storategy loops `UNICODE_RANGES` and `code_map keys` indivisualy, so it takes `O(max(N, M))` time.
I measure `Problem: TTFunk::Subset#encode` time with #82 reproduction code.(English Font changed to 'spec/fonts/DejaVuSans.ttf')
It's about 8x faster than master branch, still 4x slower than 1.5.1 branch.
|branch|font|time[s]| …

Improve Performance of TTFunk::Table::OS2#group_original_code_points_by_bit

---

.github/workflows/ci.yml
lib/ttfunk/table/cff/index.rb
lib/ttfunk/table/cff/path.rb
lib/ttfunk/table/cff/top_dict.rb
lib/ttfunk/table/kern.rb
spec/ttfunk/table/cff/charset_spec.rb
spec/ttfunk/table/cff/fd_selector_spec.rb
ttfunk.gemspec

This PR bumps up prawn_dev to 0.3.0, which also bumps the minimum Ruby version to 2.6.0
It also:
1. Removes 2.5, 2.5.0, and jruby-9.2 from CI
2. Adds jruby-9.3 to CI
3. Addresses a few lints from the updated configuration

Bump up prawn_dev to 0.3.0

---

CHANGELOG.md
lib/ttfunk/table/maxp.rb
spec/ttfunk/ttf_encoder_spec.rb

Original approach was right but there was an error in field sizes. This lead to shift of the following field. One of the fields is maxStackElements which defines stack size for font program. FreeFont
(also used in Ghostscript) is very strict about stack size. Incorrect maxStackElements value lead to stack overflow in FreeFont. Consequently, Ghostscript couldn't parse the font and completely discarded it.

Fix maxp table
